import { createLeadAndAssign } from '@/lib/lead-distribution'

export async function generateConcurrentTestLeads(total = 10) {
  const createdAtSeed = Date.now()
  const jobs = Array.from({ length: total }, (_, index) => {
    const serviceId = (index % 3) + 1
    const suffix = String(createdAtSeed + index)
    const phoneNumber = `88${suffix.slice(-8)}`

    return createLeadAndAssign({
      name: `Load Test User ${index + 1}`,
      phoneNumber,
      city: ['London', 'Manchester', 'Leeds'][index % 3],
      serviceId,
      description: `Generated by the concurrency test runner #${index + 1}`,
    })
      .then((result) => ({
        ok: true,
        leadId: result.leadId,
        serviceId,
      }))
      .catch((error: unknown) => ({
        ok: false,
        serviceId,
        message: error instanceof Error ? error.message : 'Unknown error',
      }))
  })

  return Promise.all(jobs)
}
